# config/application.yml
defaults: &defaults
  capistrano:
    app_name: 'app_name'
    repo_url: 'git@github.com:FunnyQ/NAME_HERE.git'
    deploy_to: '/home/deployer/PATH_HERE'
    role: 'role@your.domain'
    server: 'your.domain'
    user: 'userName'

  mysql:
    database:
    password:
    username:

  facebook:
    app_id:
    secret:

  disqus:
    short_name:
    secret_key:
    public_key:
    access_token:

  secret_key: '4190de7294576817164261152b2a5d36d61ec6be54d336e514e15f662618df30bf3c33502853aa8c1321263bc4a90702c0205e110ee1f61f177cbfde9ae36a05'

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
  secret_key: # rake secret to generate one
