# config/application.yml
defaults: &defaults
  capistrano:
    app_name: 'app_name'
    repo_url: 'git@github.com:FunnyQ/NAME_HERE.git'
    deploy_to: '/home/deployer/PATH_HERE'
    role: 'role@your.domain'
    server: 'your.domain'
    user: 'userName'

  mysql:
    detabase:
    password:
    username:

  facebook:
    app_id:
    secret:

  disqus:
    short_name:
    secret_key:
    public_key:
    access_token:

development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults
